### PR TITLE
Fixing 1.8. It is able to work right now!

### PR DESCRIPTION
**Pull request by dsolmann**
Big thanks to @maschmi, who made it possible.

### CODE REVIEW

**Comment by kawarantik** [comment]
Does this mean that the mod can be used in the 1.8 version of the game? I couldn't get it to work.

**Comment by maschmi** [comment]
@todiwan I've just compiled the current master with KSP v1.8.1.2694 (LinuxPlayer) and was able to select the Telemachus TeleBlade Antenna and open the browser via "Open Link" and get telemetry data.
Which OS and KSP version are you using?

**Comment by maschmi** [comment]
@todiwan One more question: Did you compile the plugin yourself or did you use the zip from the releases? Seems to me the last release was in April.
If you like you can try the attached zip file. Just extract it to the GameData folder of KSP.
[Telemachus-KSP1.8.zip](https://github.com/TeleIO/Telemachus-1/files/3945911/Telemachus-KSP1.8.zip)

**Comment by StoneBlue** [comment]
@maschmi Just wondering if the .dll packaged in the .zip you link above is actually the correct one?
Its dated 12/01/19, yet per your above message from 2hrs ago, you say "...just compiled.." ... ??
Just wanted to clarify whether that was an issue or not ;) 
Thanx for your changes :thumbs_up:

**Comment by dsolmann** [comment]
I can't publish release yet, because an AppVeyor is not properly working. Usually, I just wait till AppVeyor says that build is done and after that, I'm just publishing Artifacts. Right now it's broken. Solutions are: wait for the official build or use @maschmi's one.

**Comment by maschmi** [comment]
@StoneBlue I should not work after work. The zipped package was the one from my first compilation. Please find the freshly compiled attached. 

[Telemachus-KSP1.8_master.zip](https://github.com/TeleIO/Telemachus-1/files/3951249/Telemachus-KSP1.8_master.zip)

**Comment by StoneBlue** [comment]
@maschmi  LOL ... :P 
I *know* that feeling...

thanx for the repack ;)

**Comment by kawarantik** [comment]
@maschmi I didn't compile it, I'm not really a dev/coder (I do know C++ but that's it, and I don't really use it). Tbh I thought I could just download the master .zip and use it as a mod. I downloaded your repack and will try it. I found the github by googling for the 1.8 version of Telemachus. How come you compiled it when Dan says it's not ready for the official build? I'm just curious. Hopefully it's not risky to add to my game. Either way, thanks!

**Comment by dsolmann** [comment]
@todiwan :
> @maschmi I didn't compile it, I'm not really a dev/coder (I do know C++ but that's it, and I don't really use it). Tbh I thought I could just download the master .zip and use it as a mod. I downloaded your repack and will try it. I found the github by googling for the 1.8 version of Telemachus. How come you compiled it when Dan says it's not ready for the official build? I'm just curious. Hopefully it's not risky to add to my game. Either way, thanks!

I m not saying, that his build is not working. I'm saying that the automatic building pipeline is broken/ 
So I'd suggest you use @maschmi's build right now until I'll fix DevOps stuff.

**Comment by ElijahTailor** [comment]
> 
> 
> @StoneBlue I should not work after work. The zipped package was the one from my first compilation. Please find the freshly compiled attached.
> 
> [Telemachus-KSP1.8_master.zip](https://github.com/TeleIO/Telemachus-1/files/3951249/Telemachus-KSP1.8_master.zip)

The archive has 2 files with the same name - [Telemachus/Plugins/PluginData/Telemachus/houston/assets/js/ResizeSensor.js] and [Telemachus/Plugins/PluginData/Telemachus/houston/assets/js/resizeSensor.js]. The first one is 7299 bytes, while the second - 8166 bytes. These names differ in Linux, but are the same in Windows versions, so the two files can't be used on Windows simultaneously.

**Pull request merged**
